# k3d cluster create --config k3d-config.yaml
# https://k3d.io/v5.7.3/usage/configfile

apiVersion: k3d.io/v1alpha5

kind: Simple

metadata:
  # cluster name
  name: dockercoins

image: rancher/k3s:v1.36.2-rc1-k3s1
# control plane nodes
servers: 3

# worker nodes
agents: 3

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: '60s'
  k3s:
    extraArgs:
      - arg: '--disable=traefik'
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
# volumes:
#   - volume: /workspace/k3d/data:data
#     nodeFilters:
#       - agent:*
