# k3d cluster create --config k3d-config.yaml
# https://k3d.io/v5.7.3/usage/configfile

apiVersion: k3d.io/v1alpha5

kind: Simple

metadata:
  name: dockercoins # cluster name

image: rancher/k3s:v1.30.3-k3s1

servers: 3 # control plane nodes

agents: 3 # worker nodes

ports:
  - port: 8082:30080
    nodeFilters:
      - agent:0
options:
  k3d: # k3d runtime settings
    wait: true # wait for cluster to be usable before returning; same as `--wait` (default: true)
  #   timeout: '60s' # wait timeout before aborting; same as `--timeout 60s`
  #   disableLoadbalancer: true # same as `--no-lb`
  #   disableImageVolume: false # same as `--no-image-volume`
  #   disableRollback: false # same as `--no-Rollback`
  #   loadbalancer:
  #     configOverrides:
  #       - settings.workerConnections=2048
  # k3s: # options passed on to K3s itself
  #   extraArgs: # additional arguments passed to the `k3s server|agent` command; same as `--k3s-arg`
  #     - arg: '--disable=traefik' # same as `--disable=traefik@server:*`
  #       nodeFilters:
  #         - server:*
