---
apiVersion: v1
kind: Service
metadata:
  name: rng
spec:
  type: ClusterIP
  selector:
    app: rng
  ports:
    - protocol: TCP
      # port of the service
      port: 80
      # port of the pod
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
spec:
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
        - name: rng
          image: dockercoins/rng:v0.1
          # resources:
          #   limits:
          #     memory: '128Mi'
          #     cpu: '500m'
          ports:
            - containerPort: 80
